### ISSUE TITLE
Can't minify ES6/7?

### ISSUE THREAD

**Issue by dandart** [ben-ng/minifyify#111]
Hi,

I'm using minifyify with browserify and babelify using grunt like this:

browserify: {
            options: {
                debug: true,
                sourceMap: true,
                transform: [
                    [
                        'babelify',
                        {
                            presets: [
                                'stage-0'
                            ]
                        }
                    ]
                ],
                plugin: [
                    [
                        'minifyify'
                    ]
                ]
            },
            app: {
                files: {
                    'compiled/index.js': 'src/public/js/index.js'
                }
            }
        },

However I can't minify ES6 files, I get an error like:
uglify-js failed on src/public/js/index.js : Unexpected token

about my import statements.

Is there any way to tell uglify we should be using es6/7?

Cheers

**Comment by ben-ng** [comment]
How strange, I'm doing this just fine. Perhaps the problem is that you have ES6/7 in your dependencies? I know I ran into problems where babel wouldn't touch those files, but uglify would later on.

**Comment by dandart** [comment]
I do indeed have ES6/7 in my deps. All I wanted was a minifiable and debuggable bunch of compiled assets!

**Comment by ben-ng** [comment]
Ah, okay. That isn't something that minifyify can help with, you need to work with babel to make sure that stuff is transpiled to ES5 first.

**Comment by kathiedart** [comment]
I've been trying it again and seems using it as a browserify plugin as well as babelify like this:

browserify --no-bundle-external -d  -t babelify -t browserify-ng-html2js -p [minifyify --map /js/index.min.js.map --output public/js/index.min.js.map] public/src/js/index.js > public/js/index.js

which I'd expect it would be fine with as it would be being sent valid ES2015... and fails upon the first word "app".

Is the solution to assign some sort of ordering so that it will run "after" the transpilation?

**Comment by ben-ng** [comment]
I'm not aware of an option to order plugins. If I recall, babel does not by default transpile your dependencies (it ignores node_modules). That sounds like one way to fix this, aside from convincing module authors to continue targeting ES5 until ES6 adoption is more widespread.
